version: '3.7'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Guayaquil
    ports:
      - 5432:5432

volumes:
  postgres:
